blank_issues_enabled: true
contact_links:
  - name: Chat with the community
    url: https://osquery.slack.com/join/shared_invite/zt-h29zm0gk-s2DBtGUTW4CFel0f0IjTEw#/
    about: Please ask and answer questions here.
