apiVersion: v1
entries:
  fleet:
  - apiVersion: v1
    appVersion: v4.2.1
    created: "2021-08-14T16:14:47.785113351Z"
    description: A Helm chart for Fleet
    digest: 53efe4ebf5037b3ec898d205fcd52197ab3917fd0557ac53ab94e44005103b7f
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.2.1.tgz
    version: v4.2.1
  - apiVersion: v1
    appVersion: v4.2.0
    created: "2021-08-14T16:14:47.784041239Z"
    description: A Helm chart for Fleet
    digest: a79c5ff7f51cce8fb783d4f133ca7d9b8a13afaa00a30e1dd8687bf592b066cc
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.2.0.tgz
    version: v4.2.0
  - apiVersion: v1
    appVersion: v4.1.0
    created: "2021-08-14T16:14:47.783010326Z"
    description: A Helm chart for Fleet
    digest: 153a557d6e028de20737b5c926e5b83cfa13062e4a1e181fbcfcca7a45d7da82
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.1.0.tgz
    version: v4.1.0
  - apiVersion: v1
    appVersion: v4.0.1
    created: "2021-08-14T16:14:47.781989514Z"
    description: A Helm chart for Fleet
    digest: 658d14ec23500f8a51b4223a2cb3c1c237290a53d4d96ea538f0f6ab2d668aff
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.0.1.tgz
    version: v4.0.1
  - apiVersion: v1
    appVersion: v4.0.0
    created: "2021-08-14T16:14:47.780973001Z"
    description: A Helm chart for Fleet
    digest: 2fdfa130b9129d91b66cf8d8555f3aee2dac2b555109fba47014163a9dfa9693
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.0.0.tgz
    version: v4.0.0
  - apiVersion: v1
    appVersion: 3.13.0
    created: "2021-08-14T16:14:47.778994778Z"
    description: A Helm chart for Fleet
    digest: 267e5d03f072d7dd9e28bc195eaa0efc1338e7eb067e7ee2e9f4dcd9f74437e5
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-3.13.0.tgz
    version: 3.13.0
  - apiVersion: v1
    appVersion: 3.12.0
    created: "2021-08-14T16:14:47.777930565Z"
    description: A Helm chart for Fleet
    digest: e6cf7bf7b0937a38b5421b50dfeb915fbcd1e352e8bd38f3a276fc4dedd3c466
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-3.12.0.tgz
    version: 3.12.0
  - apiVersion: v1
    appVersion: 3.11.0
    created: "2021-08-14T16:14:47.776796551Z"
    description: A Helm chart for Fleet
    digest: 739e2764437c1ca87314128c094277154d539c75c9d566b94cba874493b9d50d
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-3.11.0.tgz
    version: 3.11.0
  - apiVersion: v1
    appVersion: 3.10.1
    created: "2021-08-14T16:14:47.775605837Z"
    description: A Helm chart for Fleet
    digest: 5ecd45f5b975d29194a27cb81c5c2edb14831d9a618f73907c002d25a6e5e634
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-3.10.1.tgz
    version: 3.10.1
  - apiVersion: v1
    appVersion: 3.10.0
    created: "2021-08-14T16:14:47.774573024Z"
    description: A Helm chart for Fleet
    digest: 743341bcd5b93270e40295214bb73ba43f7820cf509dc091f4d18d97c17b2641
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-3.10.0.tgz
    version: 3.10.0
  - apiVersion: v1
    appVersion: 3.9.0
    created: "2021-08-14T16:14:47.779919689Z"
    description: A Helm chart for Fleet
    digest: 911937bbb967a7b6478eae890553ecba88f18f2d53f8a33fb39f6dda206ff84f
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-3.9.0.tgz
    version: 3.9.0
generated: "2021-08-14T16:14:47.772643801Z"
