apiVersion: v1
entries:
  fleet:
  - apiVersion: v1
    appVersion: v4.4.2
    created: "2021-10-15T01:03:53.992673017Z"
    description: A Helm chart for Fleet
    digest: 6ec224c2ea857326d8498409e879ed1943b582a2a85cbeb96494ff70c93bc4cd
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.4.2.tgz
    version: v4.4.2
  - apiVersion: v1
    appVersion: v4.4.1
    created: "2021-10-15T01:03:53.99171408Z"
    description: A Helm chart for Fleet
    digest: d4e07cd52304d0f1ce887ff8843b231db0fbf3a474f0b12629f24370b0f85fcc
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.4.1.tgz
    version: v4.4.1
  - apiVersion: v1
    appVersion: v4.4.0
    created: "2021-10-15T01:03:53.990865747Z"
    description: A Helm chart for Fleet
    digest: c72f4d3b088195cf09247cbee0da545ce8903275d82ecf801caf50e9c4d6f7aa
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.4.0.tgz
    version: v4.4.0
  - apiVersion: v1
    appVersion: v4.3.2
    created: "2021-10-15T01:03:53.989596297Z"
    description: A Helm chart for Fleet
    digest: 4b7c770616ff52688eaea2b979c6df518e6aaabe7c627be74a04a2a552883868
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.3.2.tgz
    version: v4.3.2
  - apiVersion: v1
    appVersion: v4.3.1
    created: "2021-10-15T01:03:53.98788493Z"
    description: A Helm chart for Fleet
    digest: 0c01a1cb4ca07bbebe77bc2985cc409dffb343bb12631c71032c6b9477abee77
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.3.1.tgz
    version: v4.3.1
  - apiVersion: v1
    appVersion: v4.3.0
    created: "2021-10-15T01:03:53.986235666Z"
    description: A Helm chart for Fleet
    digest: 65519bb5d2dd5b1b5950fdedd2b01157233385ec849978c8420b2f292aced49f
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.3.0.tgz
    version: v4.3.0
  - apiVersion: v1
    appVersion: v4.2.4
    created: "2021-10-15T01:03:53.985403734Z"
    description: A Helm chart for Fleet
    digest: 77ad990623c58c53ef16109a7154a5c4993e8e30e268bf7837175192c590f191
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.2.4.tgz
    version: v4.2.4
  - apiVersion: v1
    appVersion: v4.2.3
    created: "2021-10-15T01:03:53.9845483Z"
    description: A Helm chart for Fleet
    digest: 06bf1c0ed4be9f88156e26cee0476638d3322a736ea1783f46752b540ce9896d
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.2.3.tgz
    version: v4.2.3
  - apiVersion: v1
    appVersion: v4.2.2
    created: "2021-10-15T01:03:53.983720668Z"
    description: A Helm chart for Fleet
    digest: 413e42ac901013604099680404f1ea66ffe9f9eb61ec6d627249c87cf17834cc
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.2.2.tgz
    version: v4.2.2
  - apiVersion: v1
    appVersion: v4.2.1
    created: "2021-10-15T01:03:53.982581823Z"
    description: A Helm chart for Fleet
    digest: 53efe4ebf5037b3ec898d205fcd52197ab3917fd0557ac53ab94e44005103b7f
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.2.1.tgz
    version: v4.2.1
  - apiVersion: v1
    appVersion: v4.2.0
    created: "2021-10-15T01:03:53.981082465Z"
    description: A Helm chart for Fleet
    digest: a79c5ff7f51cce8fb783d4f133ca7d9b8a13afaa00a30e1dd8687bf592b066cc
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.2.0.tgz
    version: v4.2.0
  - apiVersion: v1
    appVersion: v4.1.0
    created: "2021-10-15T01:03:53.979972922Z"
    description: A Helm chart for Fleet
    digest: 153a557d6e028de20737b5c926e5b83cfa13062e4a1e181fbcfcca7a45d7da82
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.1.0.tgz
    version: v4.1.0
  - apiVersion: v1
    appVersion: v4.0.1
    created: "2021-10-15T01:03:53.97891168Z"
    description: A Helm chart for Fleet
    digest: 658d14ec23500f8a51b4223a2cb3c1c237290a53d4d96ea538f0f6ab2d668aff
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.0.1.tgz
    version: v4.0.1
  - apiVersion: v1
    appVersion: v4.0.0
    created: "2021-10-15T01:03:53.977763635Z"
    description: A Helm chart for Fleet
    digest: 2fdfa130b9129d91b66cf8d8555f3aee2dac2b555109fba47014163a9dfa9693
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-v4.0.0.tgz
    version: v4.0.0
  - apiVersion: v1
    appVersion: 3.13.0
    created: "2021-10-15T01:03:53.975978666Z"
    description: A Helm chart for Fleet
    digest: 267e5d03f072d7dd9e28bc195eaa0efc1338e7eb067e7ee2e9f4dcd9f74437e5
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-3.13.0.tgz
    version: 3.13.0
  - apiVersion: v1
    appVersion: 3.12.0
    created: "2021-10-15T01:03:53.975038129Z"
    description: A Helm chart for Fleet
    digest: e6cf7bf7b0937a38b5421b50dfeb915fbcd1e352e8bd38f3a276fc4dedd3c466
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-3.12.0.tgz
    version: 3.12.0
  - apiVersion: v1
    appVersion: 3.11.0
    created: "2021-10-15T01:03:53.973490869Z"
    description: A Helm chart for Fleet
    digest: 739e2764437c1ca87314128c094277154d539c75c9d566b94cba874493b9d50d
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-3.11.0.tgz
    version: 3.11.0
  - apiVersion: v1
    appVersion: 3.10.1
    created: "2021-10-15T01:03:53.971629296Z"
    description: A Helm chart for Fleet
    digest: 5ecd45f5b975d29194a27cb81c5c2edb14831d9a618f73907c002d25a6e5e634
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-3.10.1.tgz
    version: 3.10.1
  - apiVersion: v1
    appVersion: 3.10.0
    created: "2021-10-15T01:03:53.970369647Z"
    description: A Helm chart for Fleet
    digest: 743341bcd5b93270e40295214bb73ba43f7820cf509dc091f4d18d97c17b2641
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-3.10.0.tgz
    version: 3.10.0
  - apiVersion: v1
    appVersion: 3.9.0
    created: "2021-10-15T01:03:53.976786397Z"
    description: A Helm chart for Fleet
    digest: 911937bbb967a7b6478eae890553ecba88f18f2d53f8a33fb39f6dda206ff84f
    home: https://github.com/fleetdm/fleet
    keywords:
    - fleet
    - osquery
    name: fleet
    sources:
    - https://github.com/fleetdm/fleet.git
    urls:
    - https://fleetdm.github.io/fleet/charts/fleet-3.9.0.tgz
    version: 3.9.0
generated: "2021-10-15T01:03:53.968991293Z"
