name: Test fleetctl preview

# Tests the `fleetctl preview` command with latest npm released version of fleetctl.

on:
  pull_request:
    paths:
      - '.github/workflows/fleetctl-preview.yml'
  workflow_dispatch: # Manual
  schedule:
  - cron: '0 2 * * *' # Nightly 2AM UTC

permissions:
  contents: read

jobs:
  test-preview:
    timeout-minutes: 60
    strategy:
      matrix:
        # Doesn't work on Windows because Linux Docker containers are not supported.
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Start colima
      timeout-minutes: 5
      if: contains(matrix.os, 'macos')
      run: |
        brew install docker docker-compose
        colima start

    - name: Start tunnel
      run: |
        npm install -g localtunnel
        lt --port 1337 &
        sleep 5

    - name: Test fleetctl preview
      run: |
        npm install -g fleetctl
        fleetctl preview
        sleep 10
        fleetctl get hosts | tee hosts.txt
        [ $( cat hosts.txt | grep online | wc -l) -eq 7 ]
      shell: bash

    - name: Get fleet logs
      if: always()
      run: |
        FLEET_LICENSE_KEY=foo docker compose -f ~/.fleet/preview/docker-compose.yml logs fleet01 fleet02 > fleet-logs.txt
        # Copying logs, otherwise the upload-artifact action uploads the logs in a hidden folder (.fleet)
        cp ~/.fleet/preview/orbit.log orbit.log
        cp -r ~/.fleet/preview/logs osquery_result_status_logs
      shell: bash

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v2
      with:
        name: ${{ matrix.os }}-log
        path: |
          fleet-logs.txt
          orbit.log
          osquery_result_status_logs
